INSERT INTO STUDENT VALUES ('001', 'KangKang', 'M ', 'h2');
INSERT INTO STUDENT VALUES ('002', 'Mike', 'M ', 'h2');
INSERT INTO STUDENT VALUES ('003', 'Jane', 'F ', 'h2');
INSERT INTO STUDENT VALUES ('004', 'Maria', 'F ', 'h2');